services:
  vms_ingestion:
    container_name: vms_ingestion
    environment:
      - GOOGLE_CLOUD_PROJECT=world-fishing-827
    platform: linux/amd64
    build:
      context: packages/
      dockerfile: ./pipe-vms-ingestion/Dockerfile
    entrypoint: "./scheduler.sh"
    volumes:
      - "gcp:/root/.config/"

  vms_ingestion_dev:
    container_name: vms_ingestion
    environment:
      - GOOGLE_CLOUD_PROJECT=world-fishing-827
      - LOGLEVEL=DEBUG
    platform: linux/amd64
    entrypoint: 
      - "poetry" 
      - "run"
      - "python"
      - "-u"
      - "main.py"
    build:
      context: packages/
      dockerfile: ./pipe-vms-ingestion/Dockerfile
      target: dev
    volumes:
      - "gcp:/root/.config/"
      - ./packages/libs:/app/libs
      - ./packages/pipe-vms-ingestion/assets:/app/pipe-vms-ingestion/assets
      - ./packages/pipe-vms-ingestion/common:/app/pipe-vms-ingestion/common
      - ./packages/pipe-vms-ingestion/main.py:/app/pipe-vms-ingestion/main.py
      - ./packages/pipe-vms-ingestion/tests:/app/pipe-vms-ingestion/tests
      - ./packages/pipe-vms-ingestion/vms_ingestion:/app/pipe-vms-ingestion/vms_ingestion

  # Use an external named volume so that we can share gcp auth across containers
  # Before first use, this volume must be manually created with
  #   docker volume create --name=gcp
  gcloud:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:stable
    entrypoint: gcloud
    volumes:
      - "gcp:/root/.config/"
volumes:
  gcp:
    external: true
