[tool.black]
line-length = 120
target-version = ['py39']

[tool.pylint."messages control"]
ignore = ["setup.py", "__init__.py"]
disable = "all"
enable = [
  "empty-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring"
]

[tool.isort]
profile = "black"
known_first_party = ["bigquery", "logger", "utils", "pipe-vms-ingestion"]
