# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vms_dead_letter.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15vms_dead_letter.proto\x12\x18\x63om.gfw.vms.ingestion.v3\"\xf7\x01\n\rVmsDeadLetter\x12\x12\n\nmessage_id\x18\x01 \x02(\t\x12\x19\n\x11subscription_name\x18\x02 \x02(\t\x12\x14\n\x0cpublish_time\x18\x03 \x02(\t\x12\x12\n\nattributes\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x02(\x0c\x12\x15\n\rerror_message\x18\x06 \x02(\t\x12\x13\n\x0bstack_trace\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x02(\t\x12\x15\n\rpipeline_step\x18\t \x01(\t\x12\x12\n\ngcs_bucket\x18\n \x01(\t\x12\x15\n\rgcs_file_path\x18\x0b \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vms_dead_letter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VMSDEADLETTER']._serialized_start=52
  _globals['_VMSDEADLETTER']._serialized_end=299
# @@protoc_insertion_point(module_scope)
