steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    entrypoint: ''
    script: |
      image_version=`echo $REF_NAME | grep -Eo "(develop)" || echo $REF_NAME | grep -Eo "${_PACKAGE_NAME}@([0-9].*)" | grep -Eo "([0-9].*)" || echo $SHORT_SHA`
      docker build \
        --file \
        ./packages/${_PACKAGE_NAME}/Dockerfile \
        -t \
        gcr.io/world-fishing-827/github.com/globalfishingwatch/${_PACKAGE_NAME}:$image_version \
        -t \
        gcr.io/world-fishing-827/github.com/globalfishingwatch/${_PACKAGE_NAME}:$SHORT_SHA \
        -t \
        gcr.io/world-fishing-827/github.com/globalfishingwatch/${_PACKAGE_NAME}:latest \
        ./packages 
  - name: 'gcr.io/cloud-builders/docker'
    id: push
    entrypoint: ''
    script: |
      image_version=`echo $REF_NAME | grep -Eo "(develop)" || echo $REF_NAME | grep -Eo "${_PACKAGE_NAME}@([0-9].*)" | grep -Eo "([0-9].*)" || echo $SHORT_SHA`
      docker push \
        gcr.io/world-fishing-827/github.com/globalfishingwatch/${_PACKAGE_NAME}:$image_version
      docker push \
        gcr.io/world-fishing-827/github.com/globalfishingwatch/${_PACKAGE_NAME}:$SHORT_SHA
      docker push \
        gcr.io/world-fishing-827/github.com/globalfishingwatch/${_PACKAGE_NAME}:latest

substitutions:
    _PACKAGE_NAME: pipe-vms-ingestion
options:
    automapSubstitutions: true
    substitutionOption: 'ALLOW_LOOSE'

timeout: 900s