version: '3.9'
services:
  vms_ingestion:
    container_name: vms_ingestion
    environment:
      - GOOGLE_CLOUD_PROJECT=world-fishing-827
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./pipe-vms-ingestion/Dockerfile
    entrypoint: "./scheduler.sh"
    volumes:
      - "gcp:/root/.config/"    
      - ../libs:/app/libs
      - ./assets:/app/pipe-vms-ingestion/assets
      - ./common:/app/pipe-vms-ingestion/common
      - ./main.py:/app/pipe-vms-ingestion/main.py
      - ./scheduler.sh:/app/pipe-vms-ingestion/scheduler.sh
      - ./tests:/app/pipe-vms-ingestion/tests
      - ./vms_ingestion:/app/pipe-vms-ingestion/vms_ingestion

# Use an external named volume so that we can share gcp auth across containers
# Before first use, this volume must be manually created with
#   docker volume create --name=gcp
volumes:
  gcp:
    external: true
