[tool.coverage.run]
branch = true
source = [ "vms_ingestion" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report html:'../../coverage/packages/pipe-vms-ingestion/html' --cov-report xml:'../../coverage/packages/pipe-vms-ingestion/coverage.xml' --html='../../reports/packages/pipe-vms-ingestion/unittests/html/index.html' --junitxml='../../reports/packages/pipe-vms-ingestion/unittests/junit.xml'"

[tool.poetry]
name = "pipe-vms-ingestion"
version = "1.0.0"
description = "VMS Ingestion"
authors = [ ]
license = 'Proprietary'
readme = 'README.md'
packages = [
  { include = "vms_ingestion" },
  { include = "bigquery", from = "libs/bigquery" },
  { include = "logger", from = "libs/logger" },
  { include = "utils", from = "libs/utils" },
]

  [tool.poetry.dependencies]
  python = ">=3.9,<3.11"
  apache-beam = {extras = ["gcp"], version = "2.56.0"}
  jinja2 = "^3.0.3"

  [tool.poetry.group.dev.dependencies]
  autopep8 = "2.0.2"
  flake8 = "6.0.0"
  icdiff="^2.0.7"
  pprintpp="^0.4.0"
  pytest = "7.3.1"
  pytest-sugar = "0.9.7"
  pytest-cov = "4.1.0"
  pytest-html = "3.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
