# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vms_message.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11vms_message.proto\x12\x18\x63om.gfw.vms.ingestion.v3\"\x81\x05\n\nVmsMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\t\x12\x0b\n\x03lon\x18\x03 \x01(\t\x12\x15\n\x08\x63\x61llsign\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06\x63ourse\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x65xternal_id\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x11\n\x04\x66lag\x18\x07 \x01(\tH\x03\x88\x01\x01\x12\x10\n\x03imo\x18\x08 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0binternal_id\x18\t \x01(\tH\x05\x88\x01\x01\x12\x11\n\x04mmsi\x18\n \x01(\tH\x06\x88\x01\x01\x12\x15\n\x08shipname\x18\x0b \x01(\tH\x07\x88\x01\x01\x12\x19\n\x0csource_fleet\x18\x0c \x01(\tH\x08\x88\x01\x01\x12\x17\n\x0fsource_provider\x18\r \x01(\t\x12\x15\n\rsource_tenant\x18\x0e \x01(\t\x12\x13\n\x0bsource_type\x18\x0f \x01(\t\x12\x12\n\x05speed\x18\x10 \x01(\tH\t\x88\x01\x01\x12K\n\x0c\x65xtra_fields\x18\x11 \x03(\x0b\x32\x35.com.gfw.vms.ingestion.v3.VmsMessage.ExtraFieldsEntry\x12\x13\n\x0breceived_at\x18\x12 \x01(\t\x12\x13\n\x0bingested_at\x18\x13 \x01(\t\x1a\x32\n\x10\x45xtraFieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0b\n\t_callsignB\t\n\x07_courseB\x0e\n\x0c_external_idB\x07\n\x05_flagB\x06\n\x04_imoB\x0e\n\x0c_internal_idB\x07\n\x05_mmsiB\x0b\n\t_shipnameB\x0f\n\r_source_fleetB\x08\n\x06_speedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vms_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VMSMESSAGE_EXTRAFIELDSENTRY']._loaded_options = None
  _globals['_VMSMESSAGE_EXTRAFIELDSENTRY']._serialized_options = b'8\001'
  _globals['_VMSMESSAGE']._serialized_start=48
  _globals['_VMSMESSAGE']._serialized_end=689
  _globals['_VMSMESSAGE_EXTRAFIELDSENTRY']._serialized_start=517
  _globals['_VMSMESSAGE_EXTRAFIELDSENTRY']._serialized_end=567
# @@protoc_insertion_point(module_scope)
